force-app/main/default/objects/Beast__c/Beast__c.object-meta.xml
<CustomObject>
    <label>Beast</label>
    <nameField>
        <label>Beast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beast__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beasts</relationshipLabel>
    <relationshipName>Beasts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beast__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Beasts</relationshipLabel>
    <relationshipName>Beasts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beast__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <label>Species</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Finance__c/Finance__c.object-meta.xml
<CustomObject>
    <label>Finance</label>
    <nameField>
        <label>Finance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Beast__c.field-meta.xml
<CustomField>
    <fullName>Beast__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Beast</label>
    <referenceTo>Beast__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sickness__c.field-meta.xml
<CustomField>
    <fullName>Sickness__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sickness</label>
    <referenceTo>Sickness__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Treats__c.field-meta.xml
<CustomField>
    <fullName>Treats__c</fullName>
    <formula>IF ( INCLUDES ( Product2.Treats__c , &quot;Cold&quot; ), &quot;Cold;&quot;, null) &amp;
IF ( INCLUDES ( Product2.Treats__c , &quot;Heat&quot; ), &quot;Heat;&quot;,null) &amp;
IF ( INCLUDES ( Product2.Treats__c , &quot;Fatigue&quot; ), &quot;Fatigue;&quot;,null) &amp;
IF ( INCLUDES ( Product2.Treats__c , &quot;Dizziness&quot; ), &quot;Dizziness;&quot;,null) &amp;
IF ( INCLUDES ( Product2.Treats__c , &quot;Dryness&quot; ), &quot;Dryness;&quot;,null) &amp;
IF ( INCLUDES ( Product2.Treats__c , &quot;Dampness&quot; ), &quot;Dampness;&quot;,null) &amp;
IF ( INCLUDES ( Product2.Treats__c , &quot;Rash&quot; ), &quot;Rash;&quot;,null) &amp;
IF ( INCLUDES ( Product2.Treats__c , &quot;Shedding&quot; ), &quot;Shedding;&quot;,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Treats</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sickness__c/Sickness__c.object-meta.xml
<CustomObject>
    <label>Sickness</label>
    <nameField>
        <label>Sickness Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sicknesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sickness__c/fields/Symptoms__c.field-meta.xml
<CustomField>
    <fullName>Symptoms__c</fullName>
    <label>Symptoms</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>symptoms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Centaur</fullName>
    </customValue>
    <customValue>
        <fullName>Chimera</fullName>
    </customValue>
    <customValue>
        <fullName>Dragon</fullName>
    </customValue>
    <customValue>
        <fullName>Griffin</fullName>
    </customValue>
    <customValue>
        <fullName>Hippocamp</fullName>
    </customValue>
    <customValue>
        <fullName>Horse</fullName>
    </customValue>
    <customValue>
        <fullName>Kelpie</fullName>
    </customValue>
    <customValue>
        <fullName>Leviathan</fullName>
    </customValue>
    <customValue>
        <fullName>Owl</fullName>
    </customValue>
    <customValue>
        <fullName>Pegasus</fullName>
    </customValue>
    <customValue>
        <fullName>Phoenix</fullName>
    </customValue>
    <customValue>
        <fullName>Raven</fullName>
    </customValue>
    <customValue>
        <fullName>Serpent</fullName>
    </customValue>
    <customValue>
        <fullName>Salamander</fullName>
    </customValue>
    <customValue>
        <fullName>Spider</fullName>
    </customValue>
    <customValue>
        <fullName>Wolf</fullName>
    </customValue>
    <masterLabel>species</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/symptoms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cold</fullName>
    </customValue>
    <customValue>
        <fullName>Dampness</fullName>
    </customValue>
    <customValue>
        <fullName>Dizziness</fullName>
    </customValue>
    <customValue>
        <fullName>Dryness</fullName>
    </customValue>
    <customValue>
        <fullName>Fatigue</fullName>
    </customValue>
    <customValue>
        <fullName>Heat</fullName>
    </customValue>
    <customValue>
        <fullName>Rash</fullName>
    </customValue>
    <customValue>
        <fullName>Shedding</fullName>
    </customValue>
    <masterLabel>symptoms</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/RecordController.cls
public without sharing class RecordController {
    
    @AuraEnabled(cacheable=true)
    public static List<PricebookEntry> getStandardProducts() {
        Pricebook2 pb = [select Id from PriceBook2 where IsStandard=True LIMIT 1];
        List<PricebookEntry> products = [SELECT Id, Name, UnitPrice, Product2Id, Treats__c FROM PricebookEntry WHERE Pricebook2Id =: pb.Id];
        return products;
    }
    
    @AuraEnabled
    public static Opportunity getNewOppty() {
        
        // get random beast
        List<Beast__c> beasts = [select Id, Name, Species__c, Contact__c, Account__c from Beast__c];
        Integer index = (Math.random() * (beasts.size() - 1)).intValue();
        
        // if beast has existing opportunity, return it
        List<Opportunity> existingOpptys = [select Id, StageName, Beast__c, AccountId, Sickness__c, Result__c from Opportunity where Beast__c =: beasts[index].Id and StageName = 'Sick'];
        if(existingOpptys.size() > 0) return existingOpptys[0];
        
		// otherwise make a new one
        Opportunity newOppty = new Opportunity();
        
        newOppty.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Medical Opportunity').getRecordTypeId();        
        newOppty.Pricebook2Id = [select Id from Pricebook2 limit 1].id;
        newOppty.Name = DateTime.now() + '';
        newOppty.CloseDate = Date.today() + 300;
        newOppty.StageName = 'Sick';
        newOppty.Result__c = 0;
        
        newOppty.Beast__c = beasts[index].Id;
        
        newOppty.AccountId = beasts[index].Account__c;
        
        List<Sickness__c> sicknesses = [select Id, Name, Symptoms__c from Sickness__c];
        index = (Math.random() * (sicknesses.size() - 1)).intValue();
        newOppty.Sickness__c = sicknesses[index].Id;
        
        insert newOppty;

        return newOppty;
    }
    
    @AuraEnabled(cacheable=true)
    public static Finance__c getFinances() {
        return [select Id, Name, Amount__c from Finance__c limit 1];
    }
    
    @AuraEnabled
    public static Finance__c setFinanceAmount(Integer profit) {
        Finance__c f = [select Id, Name, Amount__c from Finance__c limit 1];
        f.Amount__c += profit;
        update f;
        return f;
    }
    
    @AuraEnabled
    public static Account getAccountFromOppty(String opptyId) {
        System.debug(opptyId);
		Opportunity oppty = [select AccountId from Opportunity where Id =: opptyId limit 1];        
        Account acc = [select Id, Name from Account where Id =: oppty.AccountId limit 1];
        return acc;
    }
    
    @AuraEnabled
    public static Beast__c getBeastFromOppty(String opptyId) {
        System.debug(opptyId);
		Opportunity oppty = [select Beast__c from Opportunity where Id =: opptyId limit 1];        
        Beast__c beast = [select Id, Name, Contact__c, Species__c from Beast__c where Id =: oppty.Beast__c limit 1];
        return beast;
    }
    
    @AuraEnabled
    public static Sickness__c getSicknessFromOppty(String opptyId) {
        System.debug(opptyId);
		Opportunity oppty = [select Sickness__c from Opportunity where Id =: opptyId limit 1];        
        Sickness__c sickness = [select Id, Name, Symptoms__c from Sickness__c where Id =: oppty.Sickness__c limit 1];
        return sickness;
    }
    
    @AuraEnabled
    public static Contact getContactFromBeast(String beastId) {
        System.debug(beastId);
		Beast__c beast = [select Contact__c, Account__c from Beast__c where Id =: beastId limit 1];
        
        if(beast.Contact__c != null) return [select Id, FirstName, LastName from Contact where Id =: beast.Contact__c limit 1];
        
        List<Contact> contacts = [select Id, FirstName, LastName from Contact where AccountId =: beast.Account__c];
        Integer index = (Math.random() * (contacts.size() - 1)).intValue();
        return contacts[index];
    }
    
}